export const projects = [
  {
    title: 'Travel Advisor',
    description: "This is an advanced Travel Companion Application created using ReactJS. It list all the nearby hotels, restaurants and attractions.",
      image: '/images/1.png',
      tags: ['Express', 'React', 'Node', 'RapidAPI', 'Maps'],
    source: 'https://github.com/UtkarshPathrabe/travel_advisor',
    visit: 'https://utkarsh-travel-advisor.netlify.app/',
    id: 0,
  },
  {
    title: 'Realtor',
    description: "This is a Real-Estate Application created using NextJS and ReactJS. It lists all the real estate available for sale and rent in UAE.",
    image: '/images/2.jpg',
    tags: ['React', 'NextJS', 'RapidAPI'],
    source: 'https://github.com/UtkarshPathrabe/utkarsh_realestate',
    visit: 'https://utkarsh-realestate.vercel.app/',
    id: 1,
  },
  {
    title: 'Realtime Chat',
    description: "This Realtime Chat Application is using ReactJS on the front end and NodeJS + Socket.io web socket library on the back end.",
      image: '/images/3.png',
      tags: ['React', 'SocketIO', 'Express', 'Node'],
    source: 'https://github.com/UtkarshPathrabe/utkarsh-react-chat-application',
    visit: 'https://utkarsh-react-chat-app.netlify.app/',
    id: 2,
  },
  {
    title: 'Speech Recognition',
    description: "This application is using SpeechRecognition interface of the Web Speech API which enables to incorporate voice data into web apps.",
    image: '/images/4.png',
    tags: ['JavaScript', 'Web Speech API'],
    source: 'https://github.com/UtkarshPathrabe/Speech-Recognition',
    visit: 'https://speech-recognition-js.herokuapp.com/',
    id: 3,
  },
  {
    title: 'Photo Booth',
    description: "This application allows users to capture their photos using various available filters.",
    image: '/images/5.png',
    tags: ['JavaScript'],
    source: 'https://github.com/UtkarshPathrabe/Photo-Booth',
    visit: 'https://photo-booth-js.herokuapp.com/',
    id: 4,
  },
  {
    title: 'World Clock',
    description: "This application shows the current time in different time zones of the world.",
    image: '/images/6.png',
    tags: ['JavaScript'],
    source: 'https://github.com/UtkarshPathrabe/World-Clock-Time-Display',
    visit: 'https://utkarshpathrabe.github.io/World-Clock-Time-Display/',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2014, timeLine: 'May 2014 - Jul 2014', text: 'Summer Intern at CMC Ltd., Mumbai', },
  { year: 2015, timeLine: 'Jun 2015 - Jul 2015', text: 'Data Analyst Summer Intern at InfoCepts Technologies Pvt. Ltd., Nagpur', },
  { year: 2016, timeLine: 'Jan 2016 - Jun 2016', text: 'Intern at J P Morgan Chase & Co., Mumbai', },
  { year: 2016, timeLine: 'Jun 2016 - Jan 2020', text: 'Associate Software Engineer at J P Morgan Chase & Co., Bengaluru', },
  { year: 2020, timeLine: 'Jan 2020 - Mar 2021', text: 'Senior Associate Software Engineer at J P Morgan Chase & Co., Bengaluru', },
  { year: 2021, timeLine: 'Mar 2021 - Present', text: 'Senior System Software Engineer at NVIDIA Graphics Pvt. Ltd., Pune', },
];