export const projects = [
    {
      title: 'Travel Advisor',
      description: "This is an advanced Travel Companion Application created using ReactJS. It list all the nearby hotels, restaurants and attractions.",
        image: '/images/projects/1.png',
        tags: ['Express', 'React', 'Node', 'RapidAPI', 'Maps'],
      source: 'https://github.com/UtkarshPathrabe/travel_advisor',
      visit: 'https://utkarsh-travel-advisor.netlify.app/',
      id: 0,
    },
    {
      title: 'Realtor',
      description: "This is a Real-Estate Application created using NextJS and ReactJS. It lists all the real estate available for sale and rent in UAE.",
      image: '/images/projects/2.jpg',
      tags: ['React', 'NextJS', 'RapidAPI'],
      source: 'https://github.com/UtkarshPathrabe/utkarsh_realestate',
      visit: 'https://utkarsh-realestate.vercel.app/',
      id: 1,
    },
    {
      title: 'Realtime Chat',
      description: "This Realtime Chat Application is using ReactJS on the front end and NodeJS + Socket.io web socket library on the back end.",
        image: '/images/projects/3.png',
        tags: ['React', 'SocketIO', 'Express', 'Node'],
      source: 'https://github.com/UtkarshPathrabe/utkarsh-react-chat-application',
      visit: 'https://utkarsh-react-chat-app.netlify.app/',
      id: 2,
    },
    {
      title: 'Weather App PWA',
      description: "Get current weather information using this Progressive Web App (PWA) created using ReactJS.",
        image: '/images/projects/9.png',
        tags: ['React', 'PWA', 'WeatherAPI'],
      source: 'https://github.com/UtkarshPathrabe/Weather-App-PWA',
      visit: 'https://utkarsh-weather-app-pwa.netlify.app/',
      id: 9,
    },
    {
      title: 'Local Tapas',
      description: "Local Storage and Event Delegation JavaScript concepts are used in this Local Tapas website.",
      image: '/images/projects/10.png',
      tags: ['JavaScript', 'Local Storage', 'Event Delegation'],
      source: 'https://github.com/UtkarshPathrabe/Local-Tapas---JS-Local-Storage-and-Event-Delegation',
      visit: 'https://utkarshpathrabe.github.io/Local-Tapas---JS-Local-Storage-and-Event-Delegation/',
      id: 10,
    },
    {
      title: 'Slide in on Scroll',
      description: "Slide in on Scroll created using HTML, CSS and JavaScript.",
      image: '/images/projects/11.gif',
      tags: ['JavaScript', 'Scrolling', 'CSS'],
      source: 'https://github.com/UtkarshPathrabe/Slide-in-on-Scroll',
      visit: 'https://utkarshpathrabe.github.io/Slide-in-on-Scroll/',
      id: 11,
    },
    {
      title: 'Speech Recognition',
      description: "This application is using SpeechRecognition interface of the Web Speech API which enables to incorporate voice data into web apps.",
      image: '/images/projects/4.png',
      tags: ['JavaScript', 'Web Speech API'],
      source: 'https://github.com/UtkarshPathrabe/Speech-Recognition',
      visit: 'https://speech-recognition-js.herokuapp.com/',
      id: 3,
    },
    {
      title: 'Mouse Shadow',
      description: "Mouse Shadow created using JavaScript.",
      image: '/images/projects/12.gif',
      tags: ['JavaScript', 'CSS'],
      source: 'https://github.com/UtkarshPathrabe/Mouse-Shadow',
      visit: 'https://utkarshpathrabe.github.io/Mouse-Shadow/',
      id: 12,
    },
    {
      title: 'Self Movement Data Analysis',
      description: "The goal of this project report is to predict the manner in which the participants did the physical exercises.",
      image: '/images/projects/13.png',
      tags: ['R', 'R Markdown'],
      source: 'https://github.com/UtkarshPathrabe/Practical-Machine-Learning-Johns-Hopkins-Bloomberg-School-of-Public-Health-Coursera/tree/master/Project',
      visit: 'https://rpubs.com/UtkarshPathrabe/PracticalMachineLearningProjectReport',
      id: 13,
    },
    {
      title: 'Thanos Portal Effect',
      description: "Thanos Portal Effect created using Three.js",
      image: '/images/projects/7.png',
      tags: ['ThreeJS', 'JavaScript'],
      source: 'https://github.com/UtkarshPathrabe/Thanos-Portal-Effect-using-Three.js',
      visit: 'https://thanos-portal.herokuapp.com/',
      id: 7,
    },
    {
      title: 'Basic ThreeJS',
      description: "Basic Three.JS project for learning purpose",
      image: '/images/projects/8.png',
      tags: ['ThreeJS', 'JavaScript'],
      source: 'https://github.com/UtkarshPathrabe/Basic-THREE.JS',
      visit: 'https://utkarshpathrabe.github.io/Basic-THREE.JS/',
      id: 8,
    },
    {
      title: 'Photo Booth',
      description: "This application allows users to capture their photos using various available filters.",
      image: '/images/projects/5.png',
      tags: ['JavaScript'],
      source: 'https://github.com/UtkarshPathrabe/Photo-Booth',
      visit: 'https://photo-booth-js.herokuapp.com/',
      id: 4,
    },
    {
      title: 'World Clock',
      description: "This application shows the current time in different time zones of the world.",
      image: '/images/projects/6.png',
      tags: ['JavaScript'],
      source: 'https://github.com/UtkarshPathrabe/World-Clock-Time-Display',
      visit: 'https://utkarshpathrabe.github.io/World-Clock-Time-Display/',
      id: 5,
    },
  ];