export const projects = [
    {
      title: 'Filmpire',
      description: "Filmpire is an application where you can filter movies by genres, check-out latest movies, movie and crew details and movie trailers.",
      image: '/images/projects/46.png',
      tags: ['React', 'Material UI', 'TMDB', 'Redux'],
      source: 'https://github.com/UtkarshPathrabe/Filmpire',
      visit: 'https://utkarsh-filmpire.netlify.app/',
      id: 46,
    },
    {
      title: 'Memories',
      description: "Memories is a simple social media app that allows users to post interesting events that happened in their lives.",
      image: '/images/projects/52.png',
      tags: ['React', 'Full-Stack', 'Redux', 'MERN'],
      source: 'https://github.com/UtkarshPathrabe/Memories-MERN-App',
      visit: 'https://utkarsh-memories.netlify.app/',
      id: 52,
    },
    {
      title: 'ShareMe',
      description: "Full stack Social Media application which lets users share photos like Instagram.",
      image: '/images/projects/54.png',
      tags: ['React', 'Full-Stack', 'TailwindCSS', 'Sanity'],
      source: 'https://github.com/UtkarshPathrabe/ShareMe',
      visit: 'https://utkarsh-pathrabe-shareme.netlify.app/',
      id: 54,
    },
    {
      title: 'Travel Advisor',
      description: "This is an advanced Travel Companion Application created using ReactJS. It list all the nearby hotels, restaurants and attractions.",
      image: '/images/projects/1.png',
      tags: ['Express', 'React', 'Node', 'RapidAPI', 'Maps'],
      source: 'https://github.com/UtkarshPathrabe/travel_advisor',
      visit: 'https://utkarsh-travel-advisor.netlify.app/',
      id: 1,
    },
    {
      title: 'Realtor',
      description: "This is a Real-Estate Application created using NextJS and ReactJS. It lists all the real estate available for sale and rent in UAE.",
      image: '/images/projects/2.jpg',
      tags: ['React', 'NextJS', 'RapidAPI'],
      source: 'https://github.com/UtkarshPathrabe/utkarsh_realestate',
      visit: 'https://utkarsh-realestate.vercel.app/',
      id: 2,
    },
    {
      title: 'E-Commerce',
      description: "Modern Full Stack E-Commerce Application created using NextJS, ReactJS, Sanity and Stripe.",
      image: '/images/projects/56.png',
      tags: ['React', 'NextJS', 'Sanity', 'Stripe'],
      source: 'https://github.com/UtkarshPathrabe/E-Commerce',
      visit: 'https://utkarsh-e-commerce.vercel.app/',
      id: 56,
    },
    {
      title: 'Lyriks',
      description: "Lyriks Music application created using ReactJS, Redux Toolkit, TailwindCSS and Shazam Core API from Rapid API.",
      image: '/images/projects/48.png',
      tags: ['React', 'Redux', 'RapidAPI', 'TailwindCSS'],
      source: 'https://github.com/UtkarshPathrabe/Lyriks-Music-App',
      visit: 'https://utkarsh-lyriks.netlify.app/',
      id: 48,
    },
    {
      title: 'Youtube',
      description: "Youtube clone application created using ReactJS, Material UI 5 and Youtube v3 API from Rapid API.",
      image: '/images/projects/51.png',
      tags: ['React', 'Material UI', 'RapidAPI', 'Youtube'],
      source: 'https://github.com/UtkarshPathrabe/Youtube-Clone',
      visit: 'https://utkarsh-youtube.netlify.app/',
      id: 51,
    },
    {
      title: 'CryptoKet dApp',
      description: "NFT Marketplace uses Next.js, Tailwind and popular Web3 concepts and technologies, smart contract development, Solidity, IPFS and more to facilitate trading of Non-Fungible Tokens.",
      image: '/images/projects/49.png',
      tags: ['React', 'Ethereum', 'Solidity', 'TailwindCSS'],
      source: 'https://github.com/UtkarshPathrabe/CryptoKet-NFT-Marketplace',
      visit: 'https://crypto-ket-nft-marketplace.vercel.app/',
      id: 49,
    },
    {
      title: 'Uniswap dApp',
      description: "Uniswap dApp react application with metamask pairing, live smart contract data fetching and the ability to use our own ERC20 tokens and swap them.",
      image: '/images/projects/50.png',
      tags: ['React', 'Smart-Contract', 'ERC20', 'TailwindCSS'],
      source: 'https://github.com/UtkarshPathrabe/Crypto-Exchange-Uniswap-dApp',
      visit: 'https://utkarsh-uniswap.netlify.app/',
      id: 50,
    },
    {
      title: 'Cryptoverse',
      description: "Cryptocurrency Application created using ReactJS. It provides details on the top cryptocurrencies and cryptocurrency news.",
      image: '/images/projects/34.png',
      tags: ['React', 'Cryptocurrency', 'RapidAPI', 'Node'],
      source: 'https://github.com/UtkarshPathrabe/Cryptoverse',
      visit: 'https://utkarsh-cryptoverse.netlify.app/',
      id: 34,
    },
    {
      title: 'Quizzer',
      description: "Quiz application created using ReactJS.",
      image: '/images/projects/53.png',
      tags: ['React', 'Quizzer', 'MaterialUI'],
      source: 'https://github.com/UtkarshPathrabe/Quizzer',
      visit: 'https://utkarsh-pathrabe-quizzer.netlify.app/',
      id: 53,
    },
    {
      title: 'Realtime Chat',
      description: "This Realtime Chat Application is using ReactJS on the front end and NodeJS + Socket.io web socket library on the back end.",
      image: '/images/projects/3.png',
      tags: ['React', 'SocketIO', 'Express', 'Node'],
      source: 'https://github.com/UtkarshPathrabe/utkarsh-react-chat-application',
      visit: 'https://utkarsh-react-chat-app.netlify.app/',
      id: 3,
    },
    {
      title: 'Metaversus',
      description: "Metaversus website UI created using modern NextJS 13 with Framer Motion and Tailwind CSS.",
      image: '/images/projects/55.png',
      tags: ['React', 'NextJS', 'TailwindCSS', 'FramerMotion'],
      source: 'https://github.com/UtkarshPathrabe/Metaversus',
      visit: 'https://utkarsh-metaversus.netlify.app/',
      id: 55,
    },
    {
      title: 'Golds Gym',
      description: "Golds Gym Application created using ReactJS. It provides details on the various gym exercises and provides links for youtube tutorial videos.",
      image: '/images/projects/45.png',
      tags: ['React', 'Node', 'RapidAPI', 'Gym'],
      source: 'https://github.com/UtkarshPathrabe/Golds-Gym',
      visit: 'https://utkarsh-golds-gym.netlify.app/',
      id: 45,
    },
    {
      title: 'HooBank',
      description: "Modern UI/UX Bank website created using React.js & Tailwind CSS",
      image: '/images/projects/47.png',
      tags: ['React', 'JS', 'UX/UI', 'TailwindCSS'],
      source: 'https://github.com/UtkarshPathrabe/HooBank-Website',
      visit: 'https://utkarsh-hoobank.netlify.app/',
      id: 47,
    },
    {
      title: 'Gericht Restaurant',
      description: "Modern UI/UX Restaurant Landing Page Website created using ReactJS.",
      image: '/images/projects/36.png',
      tags: ['React', 'JS', 'Responsive', 'UX/UI'],
      source: 'https://github.com/UtkarshPathrabe/Gericht-Restaurant',
      visit: 'https://utkarsh-gericht-restaurant.netlify.app/',
      id: 36,
    },
    {
      title: 'Weather App PWA',
      description: "Get current weather information using this Progressive Web App (PWA) created using ReactJS.",
      image: '/images/projects/9.png',
      tags: ['React', 'PWA', 'WeatherAPI'],
      source: 'https://github.com/UtkarshPathrabe/Weather-App-PWA',
      visit: 'https://utkarsh-weather-app-pwa.netlify.app/',
      id: 9,
    },
    {
      title: 'React Table Demo',
      description: "Demo code for different use-cases using react-table NPM package.",
      image: '/images/projects/37.png',
      tags: ['React', 'JS', 'React Table'],
      source: 'https://github.com/UtkarshPathrabe/React-Table-Demo',
      visit: 'https://utkarsh-react-table-demo.netlify.app/',
      id: 37,
    },
    {
      title: 'React Router Demo',
      description: "Demo code for different use-cases using react-router NPM package.",
      image: '/images/projects/43.png',
      tags: ['React', 'JS', 'React Router'],
      source: 'https://github.com/UtkarshPathrabe/React-Router-Demo',
      visit: 'https://utkarsh-react-router-demo.netlify.app/',
      id: 43,
    },
    {
      title: 'React Testing Library',
      description: "React Testing Library and Jest are used for unit and integration tests of a Todo App created using ReactJS.",
      image: '/images/projects/44.png',
      tags: ['React', 'JS', 'ReactTestingLibrary', 'Jest'],
      source: 'https://github.com/UtkarshPathrabe/React-Testing-Library-Demo',
      visit: 'https://utkarsh-react-testing-library-demo.netlify.app/',
      id: 44,
    },
    {
      title: 'RiceRocks',
      description: "RiceRocks game created using Python. Visit the game and click on the play button to launch the game.",
      image: '/images/projects/21.png',
      tags: ['Python'],
      source: 'https://github.com/UtkarshPathrabe/RiceRocks',
      visit: 'https://py2.codeskulptor.org/#user40_mPZsI98jU7_4.py',
      id: 21,
    },
    {
      title: 'Blackjack',
      description: "Blackjack game created using Python. Visit the game and click on the play button to launch the game.",
      image: '/images/projects/22.png',
      tags: ['Python'],
      source: 'https://github.com/UtkarshPathrabe/Blackjack-Game-using-Python',
      visit: 'https://py2.codeskulptor.org/#user40_jnSBnwnpcO_20.py',
      id: 22,
    },
    {
      title: 'Memory Game',
      description: "Memory game created using Python. Visit the game and click on the play button to launch the game.",
      image: '/images/projects/23.png',
      tags: ['Python'],
      source: 'https://github.com/UtkarshPathrabe/Memory-Game-using-Python',
      visit: 'https://py2.codeskulptor.org/#user38_vrsmncrb1m4LHu2.py',
      id: 23,
    },
    {
      title: 'Pong Game',
      description: "Pong game created using Python. Visit the game and click on the play button to launch the game.",
      image: '/images/projects/24.png',
      tags: ['Python'],
      source: 'https://github.com/UtkarshPathrabe/Pong-Game-using-Python',
      visit: 'https://py2.codeskulptor.org/#user38_VNtpAkYb9cnHgqb.py',
      id: 24,
    },
    {
      title: 'Guess the Number',
      description: "Guess the number game created using Python. Visit the game and click on the play button to launch the game.",
      image: '/images/projects/25.png',
      tags: ['Python'],
      source: 'https://github.com/UtkarshPathrabe/Guess-the-Number-Game-using-Python',
      visit: 'https://py2.codeskulptor.org/#user38_ei0dID0C2V9LNbB.py',
      id: 25,
    },
    {
      title: 'Stopwatch Game',
      description: "Stopwatch game created using Python. Visit the game and click on the play button to launch the game.",
      image: '/images/projects/26.png',
      tags: ['Python'],
      source: 'https://github.com/UtkarshPathrabe/Stopwatch-Game-using-Python',
      visit: 'https://py2.codeskulptor.org/#user39_6eqA379GiyDUay8_0.py',
      id: 26,
    },
    {
      title: 'Thanos Portal Effect',
      description: "Thanos Portal Effect created using Three.js",
      image: '/images/projects/7.gif',
      tags: ['ThreeJS', 'JavaScript'],
      source: 'https://github.com/UtkarshPathrabe/Thanos-Portal-Effect-using-Three.js',
      visit: 'https://utkarshpathrabe.github.io/Thanos-Portal-Effect-using-Three.js/',
      id: 7,
    },
    {
      title: 'Basic ThreeJS',
      description: "Basic Three.JS project for learning purpose",
      image: '/images/projects/8.gif',
      tags: ['ThreeJS', 'JavaScript'],
      source: 'https://github.com/UtkarshPathrabe/Basic-THREE.JS',
      visit: 'https://utkarshpathrabe.github.io/Basic-THREE.JS/',
      id: 8,
    },
    {
      title: 'Alfa Romeo Model',
      description: "Alfa Romeo Stradale 1967 3D Car Model created using Three.js",
      image: '/images/projects/38.png',
      tags: ['ThreeJS', 'JavaScript'],
      source: 'https://github.com/UtkarshPathrabe/Alfa-Romeo-Stradale-1967-3D-Model',
      visit: 'https://utkarshpathrabe.github.io/Alfa-Romeo-Stradale-1967-3D-Model/',
      id: 38,
    },
    {
      title: 'Porche 911 Model',
      description: "Porche 911 930 Turbo 1975 3D Car Model created using Three.js",
      image: '/images/projects/39.png',
      tags: ['ThreeJS', 'JavaScript'],
      source: 'https://github.com/UtkarshPathrabe/Porche-911-930-Turbo-1975-3D-Model',
      visit: 'https://utkarshpathrabe.github.io/Porche-911-930-Turbo-1975-3D-Model/',
      id: 39,
    },
    {
      title: 'Space Scroll Animation',
      description: "Space scroll animation created using Three.js for a dummy portfolio site.",
      image: '/images/projects/40.gif',
      tags: ['ThreeJS', 'JavaScript'],
      source: 'https://github.com/UtkarshPathrabe/Space-Scroll-Animation',
      visit: 'https://utkarshpathrabe.github.io/Space-Scroll-Animation/',
      id: 40,
    },
    {
      title: 'Arid World Model',
      description: "Arid world 3D model created using Three.js",
      image: '/images/projects/41.png',
      tags: ['ThreeJS', 'JavaScript'],
      source: 'https://github.com/UtkarshPathrabe/Arid-World-3D-Model',
      visit: 'https://utkarshpathrabe.github.io/Arid-World-3D-Model/',
      id: 41,
    },
    {
      title: 'Tropic World Model',
      description: "Tropic world 3D model created using Three.js",
      image: '/images/projects/42.png',
      tags: ['ThreeJS', 'JavaScript'],
      source: 'https://github.com/UtkarshPathrabe/Tropic-World-3D-Model',
      visit: 'https://utkarshpathrabe.github.io/Tropic-World-3D-Model/',
      id: 42,
    },
    {
      title: 'Drum Kit',
      description: "Drum Kit created using HTML, CSS and JavaScript.",
      image: '/images/projects/27.png',
      tags: ['JavaScript', 'HTML', 'CSS'],
      source: 'https://github.com/UtkarshPathrabe/Drum-Kit-JS',
      visit: 'https://utkarshpathrabe.github.io/Drum-Kit-JS/',
      id: 27,
    },
    {
      title: 'Flex Panel Gallery',
      description: "Flex Panel Image Gallery created using HTML, CSS and JavaScript.",
      image: '/images/projects/28.png',
      tags: ['JavaScript', 'HTML', 'CSS'],
      source: 'https://github.com/UtkarshPathrabe/Flex-Panel-Image-Gallery',
      visit: 'https://utkarshpathrabe.github.io/Flex-Panel-Image-Gallery/',
      id: 28,
    },
    {
      title: 'Local Tapas',
      description: "Local Storage and Event Delegation JavaScript concepts are used in this Local Tapas website.",
      image: '/images/projects/10.png',
      tags: ['JavaScript', 'Local Storage', 'Event Delegation'],
      source: 'https://github.com/UtkarshPathrabe/Local-Tapas---JS-Local-Storage-and-Event-Delegation',
      visit: 'https://utkarshpathrabe.github.io/Local-Tapas---JS-Local-Storage-and-Event-Delegation/',
      id: 10,
    },
    {
      title: 'Slide in on Scroll',
      description: "Slide in on Scroll created using HTML, CSS and JavaScript.",
      image: '/images/projects/11.gif',
      tags: ['JavaScript', 'Scrolling', 'CSS'],
      source: 'https://github.com/UtkarshPathrabe/Slide-in-on-Scroll',
      visit: 'https://utkarshpathrabe.github.io/Slide-in-on-Scroll/',
      id: 11,
    },
    {
      title: 'Speech Recognition',
      description: "This application is using SpeechRecognition interface of the Web Speech API which enables to incorporate voice data into web apps.",
      image: '/images/projects/4.png',
      tags: ['JavaScript', 'Web Speech API'],
      source: 'https://github.com/UtkarshPathrabe/Speech-Recognition',
      visit: 'https://utkarshpathrabe.github.io/Speech-Recognition/',
      id: 4,
    },
    {
      title: 'Mouse Shadow',
      description: "Mouse Shadow created using JavaScript.",
      image: '/images/projects/12.gif',
      tags: ['JavaScript', 'CSS'],
      source: 'https://github.com/UtkarshPathrabe/Mouse-Shadow',
      visit: 'https://utkarshpathrabe.github.io/Mouse-Shadow/',
      id: 12,
    },
    {
      title: 'Exercises Prediction',
      description: "The goal of this project report is to predict the manner in which the participants did the physical exercises.",
      image: '/images/projects/13.png',
      tags: ['R', 'R Markdown'],
      source: 'https://github.com/UtkarshPathrabe/Practical-Machine-Learning-Johns-Hopkins-Bloomberg-School-of-Public-Health-Coursera/tree/master/Project',
      visit: 'https://rpubs.com/UtkarshPathrabe/PracticalMachineLearningProjectReport',
      id: 13,
    },
    {
      title: 'Storm Analysis',
      description: "Report on the impact of natural disasters on the economy and the public health of the United States.",
      image: '/images/projects/14.png',
      tags: ['R', 'R Markdown'],
      source: 'https://github.com/UtkarshPathrabe/Reproducible-Research-Johns-Hopkins-Bloomberg-School-of-Public-Health-Coursera/tree/master/Project%2002',
      visit: 'https://rpubs.com/UtkarshPathrabe/Storm_Analysis',
      id: 14,
    },
    {
      title: 'Activity Monitoring',
      description: "Report answering various questions on the Activity Monitoring data.",
      image: '/images/projects/15.png',
      tags: ['R', 'R Markdown'],
      source: 'https://github.com/UtkarshPathrabe/Reproducible-Research-Johns-Hopkins-Bloomberg-School-of-Public-Health-Coursera/tree/master/Project%2001',
      visit: 'https://github.com/UtkarshPathrabe/Reproducible-Research-Johns-Hopkins-Bloomberg-School-of-Public-Health-Coursera/blob/master/Project%2001/PA1_template.md',
      id: 15,
    },
    {
      title: 'Photo Booth',
      description: "This application allows users to capture their photos using various available filters.",
      image: '/images/projects/5.png',
      tags: ['JavaScript'],
      source: 'https://github.com/UtkarshPathrabe/Photo-Booth',
      visit: 'https://utkarshpathrabe.github.io/Photo-Booth/',
      id: 5,
    },
    {
      title: 'KeySequence Detector',
      description: "Key Sequence Detector created using JavaScript.",
      image: '/images/projects/19.png',
      tags: ['JavaScript'],
      source: 'https://github.com/UtkarshPathrabe/Key-Sequence-Detection',
      visit: 'https://utkarshpathrabe.github.io/Key-Sequence-Detection/',
      id: 19,
    },
    {
      title: 'HTML Video Player',
      description: "Custom Skin for HTML Video Player created using CSS and JavaScript.",
      image: '/images/projects/20.png',
      tags: ['CSS', 'JavaScript'],
      source: 'https://github.com/UtkarshPathrabe/HTML-Video-Player',
      visit: 'https://utkarshpathrabe.github.io/HTML-Video-Player/',
      id: 20,
    },
    {
      title: 'Drawing Canvas',
      description: "Drawing Canvas created using HTML, CSS and JavaScript.",
      image: '/images/projects/29.png',
      tags: ['JavaScript', 'HTML', 'CSS'],
      source: 'https://github.com/UtkarshPathrabe/HTML5-Canvas',
      visit: 'https://utkarshpathrabe.github.io/HTML5-Canvas/',
      id: 29,
    },
    {
      title: 'Picture Frame',
      description: "Picture frame created using HTML5, CSS and JavaScript where we update CSS variables using JS.",
      image: '/images/projects/30.png',
      tags: ['JavaScript', 'HTML', 'CSS'],
      source: 'https://github.com/UtkarshPathrabe/Playing-with-CSS-Variables',
      visit: 'https://utkarshpathrabe.github.io/Playing-with-CSS-Variables/',
      id: 30,
    },
    {
      title: 'Type Ahead',
      description: "Type Ahead search created using HTML, CSS and JavaScript.",
      image: '/images/projects/31.png',
      tags: ['JavaScript', 'HTML', 'CSS'],
      source: 'https://github.com/UtkarshPathrabe/Type-Ahead-JS',
      visit: 'https://utkarshpathrabe.github.io/Type-Ahead-JS/',
      id: 31,
    },
    {
      title: 'Multi Select',
      description: "Multi Select Checkboxes created using HTML5, CSS and JavaScript.",
      image: '/images/projects/32.png',
      tags: ['JavaScript', 'HTML', 'CSS'],
      source: 'https://github.com/UtkarshPathrabe/Hold-Shift-and-Check-Checkboxes',
      visit: 'https://utkarshpathrabe.github.io/Hold-Shift-and-Check-Checkboxes/',
      id: 32,
    },
    {
      title: 'World Clock',
      description: "This application shows the current time in different time zones of the world.",
      image: '/images/projects/6.png',
      tags: ['JavaScript'],
      source: 'https://github.com/UtkarshPathrabe/World-Clock-Time-Display',
      visit: 'https://utkarshpathrabe.github.io/World-Clock-Time-Display/',
      id: 6,
    },
    {
      title: 'Clock',
      description: "Clock created using CSS and JS.",
      image: '/images/projects/16.png',
      tags: ['CSS', 'JavaScript'],
      source: 'https://github.com/UtkarshPathrabe/JS-and-CSS-Clock',
      visit: 'https://utkarshpathrabe.github.io/JS-and-CSS-Clock/',
      id: 16,
    },
    {
      title: 'Video Durations',
      description: "Programmatically calculate the total duration of all videos.",
      image: '/images/projects/17.png',
      tags: ['JavaScript'],
      source: 'https://github.com/UtkarshPathrabe/Total-Duration-from-Videos-List',
      visit: 'https://utkarshpathrabe.github.io/Total-Duration-from-Videos-List/',
      id: 17,
    },
    {
      title: 'List Sort',
      description: "Custom comparator for sorting a list of strings ignoring the english articles (a, an or the) in the start of the names while sorting.",
      image: '/images/projects/18.png',
      tags: ['JavaScript'],
      source: 'https://github.com/UtkarshPathrabe/Sort-List-Ignoring-Articles--A-An-The-',
      visit: 'https://utkarshpathrabe.github.io/Sort-List-Ignoring-Articles--A-An-The-/',
      id: 18,
    },
    {
      title: 'Canvas',
      description: "Colorful Canvas created using HTML, CSS and JavaScript.",
      image: '/images/projects/33.png',
      tags: ['JavaScript', 'HTML', 'CSS'],
      source: 'https://github.com/UtkarshPathrabe/Fun-with-HTML5-Canvas',
      visit: 'https://utkarshpathrabe.github.io/Fun-with-HTML5-Canvas/',
      id: 33,
    },
  ];